### ISSUE TITLE
OOP?

### ISSUE THREAD

**Issue by an-OK-squirrel** [TheGrits/SecondLayer#3]
3 reasons:
* Having saves would be easy. Each save is a different object.
* More organization. You could have 3 puzzles at the same time!
* It would be possible to re-use the objects for, say, a solver.

This is how it would work:
![slplan](https://cloud.githubusercontent.com/assets/12722625/8663241/4d88d498-298e-11e5-8732-d96f773f0844.png)
(sorry, I accidentally called it ColorCross instead of SecondLayer. :P

**Comment by TheGrits** [comment]
I wanted to make a HTML5 version, I don't think that Java is that friendly with HTML5.

**Comment by an-OK-squirrel** [comment]
```
var Person = function (firstName) {
  this.firstName = firstName;
  console.log('Person instantiated');
};

var person1 = new Person('Alice');
var person2 = new Person('Bob');

// Show the firstName properties of the objects
console.log('person1 is ' + person1.firstName); // logs "person1 is Alice"
console.log('person2 is ' + person2.firstName); // logs "person2 is Bob"

**Comment by TheGrits** [comment]
Doh. How could I make such a silly mistake. xP

**Comment by an-OK-squirrel** [comment]
Who's assigned to this?

**Comment by TheGrits** [comment]
Um... good question.

**Comment by an-OK-squirrel** [comment]
Let's put off all of this until I solve the scratch version :P

**Comment by an-OK-squirrel** [comment]
I solved it! I'll have you set up the structure, and I'll do puzzle functionality.

**Comment by TheGrits** [comment]
Nicely done! What do you mean, "set up the structure"? Do you mean that I set up board and you will do the keyboard stuff?

Also, I was thinking maybe there should be a score system. For instance, you start with 1000 points and a point get deducted for every move you do. What are your thoughts on this?

**Comment by an-OK-squirrel** [comment]
Exactly the opposite. :P You make the SecondLayerIO and SecondLayer, but I'll add the functionality (moving the pieces.)

TBH, I don't like that idea. I like the idea of it being a twisty puzzle, and the score just ruins it for me. How about a timer and move counter?

**Comment by an-OK-squirrel** [comment]
Actually, screw it. I'll make the basic structure. (Also, should we get more members?)
